### ISSUE TITLE
Disable in closing tags

### ISSUE THREAD

**Issue by dsandstrom** [bradleyflood/auto-id-class#1]
Not a big deal, but I noticed you can add id/class in the closing tag, too.

**Comment by bradfx** [comment]
Agreed. I'll see what I can do. Thanks :)

**Comment by vipuldcoder** [comment]
I also check the same

**Comment by revelt** [comment]
Finally it's fixed. We'll publish this very soon. On this occasion I want to add checks for doctype's `<!`. It will be impossible to add a class on doctype tag.

Thanks @dsandstrom and @vipuldcoder and sorry it took a while to nail this 👍

**Comment by bradfx** [comment]
Nice work @revelt

**Comment by revelt** [comment]
Thanks!
