### ISSUE TITLE
Cursor in tag will output class/id though search/cmd+p dialog has focus

### ISSUE THREAD

**Issue by bradfx** [bradleyflood/auto-id-class#3]
> If the last cursor is in an html tag, it will start a class for that tag. Even though I'm typing in the search toolbar.

To simulate: place cursor within an html tag and then use `cmd+p` and type a `.` this will output `class=""` into the previously selected html tag even though it's not in focus.

**Comment by bradfx** [comment]
Can simulate by having cursor in html tag then initiating new file dialog. Typing `.` will output in the blurred window and no . will appear in the file name.

**Comment by revelt** [comment]
It's not happening any more, Atom must have improved since. I'm closing this, but if anybody can recreate, feel free to re-open.

![bug](https://user-images.githubusercontent.com/8344688/37865273-4d00f194-2f72-11e8-9708-24e0b949fa5a.gif)

**Comment by revelt** [comment]
Oops, I had plugin disabled.. I can confirm it still happens.

**Comment by revelt** [comment]
Fixed by https://github.com/bradleyflood/auto-id-class/pull/13, closing
