### ISSUE TITLE
Disable in erb tags

### ISSUE THREAD

**Issue by dsandstrom** [bradleyflood/auto-id-class#5]
Typing a period after the `widget` in the erb tag should not add a class attribute:
```erb
<section id="widget_<%= widget. %>">
```

**Comment by revelt** [comment]
I think this issue should fall under the more generic #9 - anything within attribute values, within single or double quotes, should not be activating id/class insertion.

**Comment by revelt** [comment]
I'm having similar problems with Nunjucks, same thing, dot in attribute values.
