### ISSUE TITLE
Add support for className on .js .jsx for React

### ISSUE THREAD

**Issue by Twintails** [bradleyflood/auto-id-class#6]
Thank you. This feature should be adopted by Atom core! 

Would like to see this extended to add ` className=""` when entering a "." and ` id=""` for "#" on an HTML element in/detected-by language-babel in .js, .jsx, .babel, .es6 and so forth.

**Comment by Twintails** [comment]
https://github.com/bradleyflood/auto-id-class/pull/7

**Comment by bradfx** [comment]
Very handy. I'll check out the PR.

**Comment by bradfx** [comment]
Closed in #7
