### ISSUE TITLE
Disable within attribute value quotes

### ISSUE THREAD

**Issue by WolfieMario** [bradleyflood/auto-id-class#9]
The shortcuts activate even when the cursor is inside an attribute value.

For example, with the HTML grammar, and cursor indicated with `|` :
`<a href="|">link</a>`
This is the result of pressing `.`:
`<a href=" class="|"">link</a>`

As a result, if you try to type `<a href="../foo">link</a>`, you wind up with:
`<a href=" class="./foo"">link</a>`

**Comment by lamk** [comment]
+1
